name: Add user on monitoring PRs

on:
  pull_request:
    types: [opened]
    paths:
      - docs/configuration.md

jobs:
  add_reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Add Reviewer
        id: add_reviewer
        run: |
          reviewers="pokyy"
          pull_request_number="${{ github.event.pull_request.number }}"
          repo_full_name="${{ github.repository }}"
          token="${{ github.token }}"

          curl -X POST \
            -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"reviewers": ["'"$reviewers"'"]}' \
            "https://api.github.com/repos/$repo_full_name/pulls/$pull_request_number/requested_reviewers"
