name: Add user on monitoring PRs

on:
  pull_request:
    types: [opened]
    paths:
      - docs/configuration.md
      # - internal/operands/metrics/*
      # - internal/common/resource.go
      # - docs/metrics.md
      # - tests/metrics_test_utils.go
      # - tools/metricsdocs/*

jobs:
  add_reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Reviewer
        id: add_reviewer
        run: gh pr edit $PULL_REQUEST_NUMBER --add-reviewer pokyy
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PULL_REQUEST_NUMBER: ${{  github.event.pull_request.number }}

    # steps:
    #   - name: Add Reviewer
    #     id: add_reviewer
    #     run: |
    #       reviewers="sradco"
    #       pull_request_number="${{ github.event.pull_request.number }}"
    #       repo_full_name="${{ github.repository }}"
    #       token="${{ github.token }}"

    #       curl -X POST \
    #         -H "Authorization: Bearer $token" \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         -d '{"reviewers": ["'"$reviewers"'"]}' \
    #         "https://api.github.com/repos/$repo_full_name/pulls/$pull_request_number/requested_reviewers"
